server:
  port: 8083
  servlet:
    context-path: /milimili

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://localhost:3306/video2?useSSL=false
    username: root
    password: zhou.1113
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true